# Generated by Django 2.2.3 on 2019-07-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190725_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRatings',
            new_name='CourseRating',
        ),
    ]
