# Generated by Django 2.2.3 on 2019-07-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190725_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content_type', models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('document', 'document')], max_length=50)),
                ('course_media', models.FileField(null=True, upload_to='course_media/', verbose_name='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
    ]
